#################
# Build the app #
#################
FROM node:12 as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -f -g gulp gulp-cli typescript gulp-typescript
RUN npm install -g @angular/cli
RUN npm install
COPY . .

WORKDIR /usr/src/app/src/client
RUN rm -rf node_modules/
RUN npm install

RUN ng build --configuration production --output-path=/dist

################
# Run in NGINX #
################
FROM nginx:alpine
COPY --from=build /dist /usr/share/nginx/html

# Copy custom config to nginx
COPY /src/client/.nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 4200/tcp
EXPOSE 80/tcp

# When the container starts, replace the env.js with values from environment variables
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
